### ISSUE TITLE
IO Buffer Instantiation Override

### ISSUE THREAD

**Issue by peteut** [m-labs/nmigen#110]
What is the envisaged way to override IO buffers instantiation, like `IBUFS_GTE2` for *Xilinx_Family7*? 
For now, I reverted 3fc5f170e6a81396adf3e1d72676f55fd0534dee in my branch to allow for direct instantiation of buffers.

**Comment by whitequark** [comment]
`platform.request("foo", dir="-")` gives you an `inout` (or a `p`, `n` diffpair) that isn't connected to a buffer.

**Comment by peteut** [comment]
That perfect, thanks @whitequark.
