### ISSUE TITLE
Should memory read ports use domain="comb" or domain=None instead of synchronous=False?

### ISSUE THREAD

**Issue by whitequark** [m-labs/nmigen#116]
It feels odd to have the `memory.read_port(domain="sync", synchronous=False)` combination of arguments to be valid, and in fact that seems like it'd cause some hard to find bugs.

**Comment by sbourdeauducq** [comment]
Why not ``domain=None``? ``comb`` is a valid, albeit ill-chosen, name for a synchronous domain.

**Comment by whitequark** [comment]
@sbourdeauducq Because of the way `Module` is implemented, trying to do `m.d.comb += stmt` or `m.d["comb"] += stmt` will always add those statements to the combinatorial domain, even if there is a synchronous domain called `comb`.

So I wouldn't say it's valid, and further, we probably need to disallow either creating a `ClockDomain("comb")` or adding it to any module.

**Comment by whitequark** [comment]
Closing per IRC discussion.
