### ISSUE TITLE
"comb" should not be accepted as a name in ClockDomain(), DomainRenamer(), etc

### ISSUE THREAD

**Issue by whitequark** [m-labs/nmigen#125]
See #116 for motivation.

**Comment by sbourdeauducq** [comment]
Why not just use ``None`` instead in memory read ports?

**Comment by whitequark** [comment]
@sbourdeauducq But that would still be a problem. Consider this code:
```
m = Module()
m.d.comb += a.eq(1)
m2 = DomainRenamer({"comb":"sync"})(m)
```
It wouldn't work the same as:
```
m2 = Module()
m2.d.sync += a.eq(1)
```
In fact this use of `DomainRenamer` is currently a no-op.

So regardless of the decision for #116, *something* needs to be fixed there, one way or another. (You could argue that this use of `DomainRenamer` should be valid--although I find it unconvincing--and then it would need to be fixed to accept such code.)
