### ISSUE TITLE
Add `-bin_file` In Vivado Flow?

### ISSUE THREAD

**Issue by peteut** [m-labs/nmigen#139]
As per b404d603fb9411dce123fd7939f5aaa54fdb87ee the Spartan 3|6 *ISE* flow adds the binary file unconditionally. 
Maybe add the `-bin_file` in the *Vivado* flow as well?
https://github.com/m-labs/nmigen/blob/b404d603fb9411dce123fd7939f5aaa54fdb87ee/nmigen/vendor/xilinx_7series.py#L95

**Comment by whitequark** [comment]
No objection.

**Comment by peteut** [comment]
Great, I'll prepare a PR then.
