### ISSUE TITLE
Question: How to change FIFO clock dommains?

### ISSUE THREAD

**Issue by andresdemski** [m-labs/nmigen#151]
Hello
I'm starting using nMigen and i want instantiate the AsyncFifoBuffered library. I found that the fifo clock domain are `read` and  `write`, and i need to connect them to domains called `input` and `output`. 

* Is there any easy way to make this connection? 
* Should libraries have an argument to specify the domain names? 

Thx.
Andres

**Comment by peteut** [comment]
@andresdemski you are looking for 

```python
m.submodules += DomainRenamer({"read": "input", "write": "output"})(<your-module>)
```

**Comment by andresdemski** [comment]
With this approach, you always need to know the implementation (or it needs to be well documented). A domain argument in libraries should be a good idea.

**Comment by whitequark** [comment]
@andresdemski I entirely agree, #97 is the tracking issue for adding an explicit argument.

**Comment by andresdemski** [comment]
Ok, Thanks you!
