### ISSUE TITLE
nmigen installation seeks invalid URL

### ISSUE THREAD

**Issue by AbigailCliche** [m-labs/nmigen#177]
Hello,

I have tried running the installation commands. The first command executes, but the second command throws an exception during "Cloning https://github.com/m-labs/nmigen-boards.git to /tmp/pip-7eq86ovp-build Collecting nmigen (from nmigen-boards===7ccb0b1)". The error is "404 Client Error: Not Found for url: https://pypi.org/simple/nmigen/". Manually searching for this URL also returns a 404 error, leading me to believe nmigen has disappeared from the site. 

I tried cloning the nmigen-boards repository and running setup.py and get a warning saying "UserWarning: The version specified ('7ccb0b1') is an invalid version".

Any insight would be helpful. Thank you.

**Comment by whitequark** [comment]
> Manually searching for this URL also returns a 404 error, leading me to believe nmigen has disappeared from the site.

It was actually never deployed because nMigen has not yet seen a single release (see #113).

> I tried cloning the nmigen-boards repository and running setup.py and get a warning saying "UserWarning: The version specified ('7ccb0b1') is an invalid version".

This is the correct workaround for the time being. After nMigen 0.1 is released it will no longer be necessary.
