### ISSUE TITLE
Add a method to nmigen.build to determine whether builds are possible

### ISSUE THREAD

**Issue by emilazy** [m-labs/nmigen#186]
Glasgow's [`@synthesis_test`](https://github.com/GlasgowEmbedded/Glasgow/blob/1b71f1fd65a1229e903110e82d8e58ba1195b1de/software/glasgow/applet/__init__.py#L284) is currently broken if you e.g. want to pass `YOSYS` as an environment variable. It would be nice if the build system exported something to test whether builds for a platform are possible that used the same logic as the build system (`get_tool` etc.), and maybe even supported different toolchains?

**Comment by whitequark** [comment]
Fixed in c4e8ac73.
