### ISSUE TITLE
Consider adding Default to Module in dsl.py

### ISSUE THREAD

**Issue by RobertBaruch** [m-labs/nmigen#197]
It seems to be more consistent with most other commonly-known languages to have the syntax for a default case look like this:
```
with m.Switch(thing):
  with m.Case(1):
    ...
  with m.Case(2):
    ...
  with m.Default():
    ...
```

than this:
```
with m.Switch(thing):
  with m.Case(1):
    ...
  with m.Case(2):
    ...
  with m.Case("default"):
    ...
```

**Comment by whitequark** [comment]
Hm, makes sense.

**Comment by whitequark** [comment]
Actually, hang on.

`with m.Case("default"):` is not valid in nMigen (this seems to be a mix of syntax from oMigen and nMigen), what you can do is `with m.Case():`.

**Comment by programmerjake** [comment]
if `with m.Case():` is going to be the way to get a default case, that needs to be documented somewhere, I was not aware that nmigen supported default cases at all.

I personally prefer having a separate `Default` function, since that is more explicit.

**Comment by whitequark** [comment]
I think having a `Default()` function as an alias for `Case()` is fine.

**Comment by RobertBaruch** [comment]
Ah, ok. I had a suspicion that default wasn't actually supported in nMigen (since I couldn't find `"default"` in the source) so I fell back to the Migen docs. So now you fixed two issues :D
