### ISSUE TITLE
Formatting settings?

### ISSUE THREAD

**Issue by RobertBaruch** [m-labs/nmigen#209]
Does the project use yapf, autopep8, or black for standard auto-formatting? Any special parameters passed to these?

**Comment by whitequark** [comment]
I don't use autoformatters, most of them are downright terrible. clang-format is okay but this isn't a C project.

**Comment by cr1901** [comment]
@whitequark Thoughts on adding a flake8 step to Travis that checks immediately whether the code is properly formatted (based on the rules you decide- i.e. remove the restrictive 80 char per line limit), and fails if it's not?

**Comment by whitequark** [comment]
I'm not sure if there's much point to it.

**Comment by RobertBaruch** [comment]
I prefer to leave formatting up to the auto-formatter so that I don't have to do any formatting myself. Specifying the project policy as no auto-formatting, though, is perfectly fine. I'll just have to remember to turn the auto-formatter off when I write code for nMigen :)

**Comment by whitequark** [comment]
Yeah, I would prefer no autoformatting for now. Could perhaps be changed in the future.

**Comment by whitequark** [comment]
Somewhat annoyingly, `nmigen-boards` *would* benefit from autoformatting, but any Python autoformatter I know of would mess up the board definitions badly.

**Comment by RobertBaruch** [comment]
That's what [`# yapf: disable` and `# yapf: enable`](https://github.com/google/yapf#why-does-yapf-destroy-my-awesome-formatting) are for :)

**Comment by whitequark** [comment]
What's the point of using yapf if you disable it on 99% of code?

**Comment by RobertBaruch** [comment]
The board files aren't 99% of the code, are they?

**Comment by whitequark** [comment]
They are 99% of code in nmigen-boards (which is a different repository with different tooling settings).
