### ISSUE TITLE
Consider supporting (* keep *)

### ISSUE THREAD

**Issue by RobertBaruch** [m-labs/nmigen#255]
See https://github.com/YosysHQ/yosys/issues/1441, where the workaround for https://github.com/m-labs/nmigen/issues/245 seems to be to declare a signal you want to keep as (* keep *).

**Comment by whitequark** [comment]
Use `signal.attrs["keep"] = 1`

**Comment by whitequark** [comment]
Does this work for you?

**Comment by whitequark** [comment]
Ping

**Comment by RobertBaruch** [comment]
Works, thanks!
