### ISSUE TITLE
Add __pycache__ to .gitignore?

### ISSUE THREAD

**Issue by mithro** [m-labs/nmigen#264]
This seems to be missing?

**Comment by whitequark** [comment]
Doesn't `*.pyc` cover it?

**Comment by mithro** [comment]
It is unclear to me if `__pycache__` can potentially have `.pyd` and `.pyo` or other files in it too? 

The default .gitignore GitHub suggests;
https://github.com/github/gitignore/blob/379476851036fbc638d258f0547d91c2a3765a33/Python.gitignore#L1-L3

```.gitignore
# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
```
