### ISSUE TITLE
Is this a bug in vendor/lattice_ice40?

### ISSUE THREAD

**Issue by RobertBaruch** [m-labs/nmigen#276]
["iCE40HX4K":  "--hx8k"](https://github.com/m-labs/nmigen/blob/master/nmigen/vendor/lattice_ice40.py#L84)

**Comment by RobertBaruch** [comment]
My bad -- it seems that lots of devices are aliased to the same flag.

**Comment by whitequark** [comment]
It's market segmentation, yes.
