### ISSUE TITLE
Signal.__doc__: Mention `range`'s `Shape.cast`able Variant

### ISSUE THREAD

**Issue by peteut** [m-labs/nmigen#288]
`Signal.__doc__` should probably mention `shape`'s `Shape.cast` able variant near ` [ast.py#L791](https://github.com/m-labs/nmigen/blob/67650214b703fee8d044fd1f165c513cc5b38964/nmigen/hdl/ast.py#L791).

**Comment by whitequark** [comment]
Fixed [upstream](https://github.com/nmigen/nmigen).
