### ISSUE TITLE
There's no explicit way to convert between signed <-> unsigned values

### ISSUE THREAD

**Issue by Maykeye** [m-labs/nmigen#292]
I have an unsigned signal. I want to compare it as signed for a change and now there are no good explicit way to do it. 

* I can make new `Signal(signed(old.width))` and `eq`uate it to the old one, but in order to do so, I must place all such signals in the beginning of elaborate: if I create a copy somewhere in the middle like `with m.If(en): comb+= make_signed_copy(n)<10`, generator will not be able to generate `wire[31:0] signed_n = n`, instead it will create `reg`ister  because if if-branch is not executed, signed_n is not being written

* There's implicit conversion: I can use `-(-n)`, and rely on optimizers down the road, but it feels hacky.

**Comment by whitequark** [comment]
Proposed API: `Value.to_signed` / `Value.to_unsigned`.
