### ISSUE TITLE
Output enable for Intel platform on multi I/O pins

### ISSUE THREAD

**Issue by schwigi** [m-labs/nmigen#297]
Not sure wether it is a bug or I have done something wrong.

I tried to get a 16 bit wide io pins, but the generated oe wire is only 1 bit. For the Intel altiobuf_bidir output enable signal must be as wide as the data lines.

Attached is a small python script to generate the output.

[ioTest.py.zip](https://github.com/m-labs/nmigen/files/4027867/ioTest.py.zip)

**Comment by peteut** [comment]
@schwigi That looks like a bug to me,`oe` should be a vector:  [nmigen.vendor.intel](https://github.com/m-labs/nmigen/blob/master/nmigen/vendor/intel.py#L279). 

![image](https://user-images.githubusercontent.com/1288741/71852823-f1bdb680-30d9-11ea-8020-a5777c8e6496.png)

Refer to ALTIOBUF IP COre User Guide, UG-01024 for details.

**Comment by schwigi** [comment]
I did some debugging runs and the problem is not in the platform.intel part.

In lib/io.py:43 the oe width is hard coded to 1. For Intel FPGAs it is clear that you must use width here as well. Not sure however how other FPGAs behave though.

**Comment by whitequark** [comment]
> I did some debugging runs and the problem is not in the platform.intel part.

No, the problem is in `vendor.intel`.

> In lib/io.py:43 the oe width is hard coded to 1.

This is deliberate: a wide tristate signal is treated as a single entity for the purposes of output enable. That is how (n)Migen define its behavior, which is completely independent of any platform. Any platform that has output enable with the same width as output should use `Repl`.

If you want to control direction per-bit, you should instantiate a tristate per bit.

**Comment by peteut** [comment]
@schwigi: shouldn't this https://github.com/m-labs/nmigen/blob/7ce75b85fc24c79ddf9bc18ff08678b739b0cd95/nmigen/vendor/intel.py#L288

also read `i_oe=self._get_oereg(m, pin),`?

**Comment by schwigi** [comment]
@peteut: You are right, get_tristate should use `_get_oereg` as well.

**Comment by ZirconiumX** [comment]
Thanks for correcting my oversight ^.^'
