### ISSUE TITLE
Module.prepare/rtlil.convert should not propagate inputs to toplevel unless explicitly requested

### ISSUE THREAD

**Issue by whitequark** [m-labs/nmigen#30]

**Comment by sbourdeauducq** [comment]
I'm also hitting this (and what is described in #35). @whitequark can you prioritize it?

**Comment by whitequark** [comment]
@sbourdeauducq Sure, I was going to fix it ASAP anyway, but haven't been able to get much done in general.

**Comment by sbourdeauducq** [comment]
This solution produces warnings such as ``Warning: Wire top.\con.arbiter.ibus__sel [3] is used but has no driver.``.

Shouldn't undriven signals take their reset value like they do in Migen?

**Comment by whitequark** [comment]
You are right. I thought they would be reset but I didn't realize that code would not run for other reasons. That's #35 then and I will fix it.
