### ISSUE TITLE
vendor.xilinx_7series: Vivado TIMING-2 Warning

### ISSUE THREAD

**Issue by peteut** [m-labs/nmigen#301]
*Vivado* issues TIMING-2 (default severity: CRITICAL) when `create_clock` uses a signal. 
Here is a potential solution to please `create_clock`: https://github.com/peteut/nmigen/commit/9e79a30655123c02a2a3025d8f5af0ce8c076b7f .

**Comment by whitequark** [comment]
Can you explain what does the filter expression in your commit does?

**Comment by peteut** [comment]
@whitequark this is indeed ugly and should be fixed, it's purpose is to filter negative ports of differential clock inputs, ending with `__n`. So it matches ports ending with `__p` or `__io`. Internal clocks are matched using `^.+/.+$`, for signals like `my_module/clk_out`.

**Comment by whitequark** [comment]
You did explain why it's ugly, which is helpful (thanks!). Unfortunately, you didn't explain what it *does*, so I can't help you work out a nicer replacement. I don't have the Xilinx flavor of Tcl API memorized.

**Comment by peteut** [comment]
Here's an excerpt from [UG906](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_2/ug906-vivado-design-analysis.pdf) explaining the TIMING-2 warning and how to use `create_clock` correctly:

![image](https://user-images.githubusercontent.com/1288741/72067853-16857a00-32e4-11ea-8173-951452f3158a.png)

The Tcl fragment does exactly that, it starts from the clock signal and determines it's startpoint using `all_fanin -flat -startpoints_only`. The returned could contains `my-signal__p my-signal__n`, therefore `filter -regexp` filters `my-signal__n`, so only a single item remain. 

```Tcl
[filter -regexp [all_fanin -flat -startpoints_only \
                    [get_nets {{signal|hierarchy("/")}}]] {NAME =~{(^.*__p$)|(^.*__io$)|(^.+/.+$)}}]
```
