### ISSUE TITLE
Case pattern syntax improvement

### ISSUE THREAD

**Issue by porglezomp** [m-labs/nmigen#316]
While I was working with cases I tried using underscores in my patterns as byte separators, expecting it to match the integer literal syntax, but it was rejected.

I'd like to be able to write patterns like `"0001_0---"`—does this seem like a good idea, or is the potential confusion between `-` and `_` a problem?

**Comment by programmerjake** [comment]
why was this closed? it seems like having a separator of some sort is a good idea.

**Comment by sbourdeauducq** [comment]
@porglezomp This repository is still maintained.
