### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by FFY00** [m-labs/nmigen#322]
Hey, I am packaging this for Arch Linux and I was wondering if there's any release planned soon? I am hoping to avoid bringing bitarray to the repositories, so if there's a release planned soon, I'll wait.

**Comment by whitequark** [comment]
You're in luck because release 0.2 already ditched bitarray! This repository lags behind the [upstream](https://github.com/nmigen/nmigen) so you don't see it here.

**Comment by FFY00** [comment]
Yes, I saw that it was removed in master.
