### ISSUE TITLE
Does nmigen support I2C  master ?

### ISSUE THREAD

**Issue by jimmymagemtek** [m-labs/nmigen#347]
Hi Sir,
Does nmigen support I2C master >
Where does it put in the directory ?

Thanks.

Jimmy

**Comment by sbourdeauducq** [comment]
I suggest you use Migen for now since nMigen has many issues and is being rewritten.
You can find example I2C code for Migen here:
https://github.com/m-labs/artiq/blob/master/artiq/gateware/drtio/wrpll/si549.py
