### ISSUE TITLE
Should nMigen check Yosys version?

### ISSUE THREAD

**Issue by mithro** [m-labs/nmigen#55]
nMigen has a pretty strong dependence on Yosys and you have been fixing a lot of bugs in it as https://github.com/m-labs/nmigen/issues/53 shows.

Maybe nMigen should check the Yosys version is new enough?

**Comment by whitequark** [comment]
Yes, but we can only pull that off after there's a release that includes the recent fixes. Unless you want to rely on the `0.8+123` notation...

**Comment by whitequark** [comment]
Triage: check will be added once there is a Yosys release.
