### ISSUE TITLE
negative values in memory initialization

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/nmigen#96]
Having a negative value in a memory initialization list produces incorrect RTLIL which is then propagated down the stack until [nextpnr crashes](https://github.com/YosysHQ/nextpnr/issues/287).
Should we support such negative values properly? They can be useful e.g. for DSP applications.

**Comment by whitequark** [comment]
Anything that's OK as a signal reset or assigned value should be OK as memory init value too. So this is clearly a bug.
