### ISSUE TITLE
Bikeshed: conventions for CDC primitives

### ISSUE THREAD

**Issue by whitequark** [m-labs/nmigen#97]
One reason I've hesitated to merge #40 so far is that I think the oMigen conventions for CDC primitives are a bit annoying. I think a better situation than the current one would be:
  * Instead of arguments named `domain`, `idomain`, `rdomain`, etc, which only allow a single letter for domain designation, use `domain`, `i_domain`, `r_domain`, `pll_domain`, etc.
  * All modules which are likely to be transformed with `DomainRenamer` right after creation should allow changing the domain names through arguments. Notably this would include `AsyncFIFO`, which is probably responsible for most uses of `DomainRenamer`, but all other CDC primitives as well. Non-CDC modules may or may not allow that depending on intended use.

Thoughts? @sbourdeauducq @jordens @Wren6991

**Comment by sbourdeauducq** [comment]
Sounds ok.

**Comment by Wren6991** [comment]
I like this, but find some of the results inconsistent (c84cd8d):

```
class Gearbox(Elaboratable):
   ...
    def __init__(self, iwidth, cd_i, owidth, cd_o):
```

Inconsistent use of suffix vs prefix is something I would trip over when typing too fast.

**Comment by whitequark** [comment]
I think `Gearbox` should of course use `width_i` and `width_o` here.
